### ISSUE TITLE
'New issue' page URL's

### ISSUE THREAD

**Issue by jonnyb023** [devlooped/ThisAssembly#108] opened 2022-06-01 19:23 UTC
## Describe the Bug

After you click the 'New issue' button, the 'Questions' and 'Ideas' buttons point to the `https://github.com/devlooped/oss` URL.

**Comment by kzu** [comment] 2022-09-04 23:01
Duplicate of https://github.com/devlooped/ThisAssembly/issues/102, fixed already.

Thanks!

**Closed by kzu** 2022-09-04 23:01 UTC
Labels: bug
