### ISSUE TITLE
CS0229: Ambiguity between 'ThisAssembly.Info.Description' and 'ThisAssembly.Info.Description' when using Unclassified.NetRevisionTask

### ISSUE THREAD

**Issue by MagicAndre1981** [devlooped/ThisAssembly#349] opened 2024-07-16 11:00 UTC
## Describe the Bug

some entries are generated twice, causing error `CS0229: Ambiguity between 'ThisAssembly.Info.Description' and 'ThisAssembly.Info.Description'`

## Steps to Reproduce

add [this config data from Unclassified.NetRevisionTask](https://github.com/ygoe/NetRevisionTask?tab=readme-ov-file#msbuild-properties) to `Directory.Build.props` :

```
<PropertyGroup>
		<NrtRevisionFormat>{semvertag}</NrtRevisionFormat>
		<NrtResolveSimpleAttributes>true</NrtResolveSimpleAttributes>
		<NrtResolveInformationalAttribute>true</NrtResolveInformationalAttribute>
		<NrtResolveCopyright>false</NrtResolveCopyright>
		<NrtTagMatch>v[0-9]*</NrtTagMatch>
		<NrtRemoveTagV>true</NrtRemoveTagV>
		<NrtRequiredVcs>svn</NrtRequiredVcs>
		<NrtShowRevision>true</NrtShowRevision>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Unclassified.NetRevisionTask" Version="0.4.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
	</ItemGroup>
```

and 

```
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyInformationalVersion("1.2.{revnum}.0")]
```
to `AssemblyInfo.cs` to let [Unclassified.NetRevisionTask ](https://www.nuget.org/packages/Unclassified.NetRevisionTask) generate the 3rd number based on the commit number from subversion (Yes, I still use subversion).

## Expected Behavior

only 1 entry in generated code

## Version Info

```
    <PackageReference Include="ThisAssembly" Version="1.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>

```

## Additional Info

![image](https://github.com/user-attachments/assets/c0a10b44-c0a1-4a68-910c-8db1c886d374)

![image](https://github.com/user-attachments/assets/cad900ec-a5e2-4254-8c05-7835935edf4f)

Here you can see the doubled entries.

I want to replace my older runtime code

```
copyrightAttribute = assembly
				.GetCustomAttributes<AssemblyCopyrightAttribute>(false)
				.FirstOrDefault();
```

to get Copyright and others with your generated code and here I noticed this conflict.

_Unclassified.NetRevisionTask_ merges all finished calculations into a file called `NrtAssemblyInfo.cs`.

So is it possible to detect this package and only use the data from the `NrtAssemblyInfo.cs`?

**Comment by MagicAndre1981** [comment] 2024-07-19 09:12
Is there a chance to fix this issue? @kzu

**Comment by kzu** [comment] 2024-07-21 06:23
I'm not familiar with what Unclassified.NetRevisionTask  does on how it works. If it's important to support that for you, I'd be glad to review and merge a PR for it.

**Comment by MagicAndre1981** [comment] 2024-07-21 22:42
> I'm not familiar with what Unclassified.NetRevisionTask does on how it works. 

as said, it [hookes into Build](https://github.com/ygoe/NetRevisionTask/blob/0657dc838261b1ec3b4a00b82f9204784c02f37e/NetRevisionTask/build/Unclassified.NetRevisionTask.targets#L62C3-L62C81) process (`<Target Name="NrtPatchAssemblyInfo" BeforeTargets="GenerateAdditionalSources">`), reads the AssemblyInfo data from the normal AssemblyInfo.cs + the dummy data and creates a new AssemblyInfo.cs where the dummy data get replaced with actual data from git or Subversion (revision), it next removed the original AssemblyInfo.cs from file list of files that should be compiled ( `<Compile Remove="$(NrtSourceAssemblyInfo)" />`) and adds the patched file (`<Compile Include="$(NrtPatchedAssemblyInfo)" />`).

Now I have 2 AssemblyInfo.cs in my project and your source generator picks data from both which causes my "Ambiguity between" error.

So maybe you can check the filenames when you read the  AssemblyInfo data and if the name is `NrtAssemblyInfo.cs` only use the data from this file and ignore the normal AssemblyInfo.cs. 

I tried source generators when they were added in .net 5 (?) and gave it up as it was horrible to debug them and so I can't really help here.

**Comment by MagicAndre1981** [comment] 2024-07-21 23:00
I've replaced the nuget references with the csproj of your generator and tried to configure the debug options of the source generator and I get a VS error:

```
Microsoft.VisualStudio.ProjectSystem.Query.QueryExecutionException: Value cannot be null.
Parameter name: value ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.EndsWith(String value, StringComparison comparisonType)
   at Roslyn.ComponentDebugger.ProjectUtilities.<GetComponentReferencingProjectsAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Roslyn.ComponentDebugger.TargetProjectEnumProvider.<GetProviderAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageDynamicEnumProperty.<GetAdmissibleEnumValueAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.PropertyPages.PageEnumPropertyBase.<GetValueAsIEnumValueAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.UIPropertyValueDataProducer.<CreateUIPropertyValueValueAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.UIPropertyValueDataProducer.<CreateUIPropertyValueValueAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.UIPropertyValueDataProducer.<CreateUIPropertyValueValuesAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Query.QueryDataFromProviderStateProducerBase`1.<SendRequestAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ProjectSystem.Query.Execution.QuerySubscription`1.<RunQueryOnceAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.Query.Execution.QuerySubscription`1.<>c__DisplayClass10_0.<<Start>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.LaunchProfileSubscription.<CreateAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.LaunchProfilesWindow.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.Designer.AsyncLoadContent.<>c__DisplayClass0_0.<<Initialize>b__0>d.MoveNext()
```

So same terrible experience again...

I need to get some sleep now as it is alreay 1am here in Germany.

**Comment by MagicAndre1981** [comment] 2024-07-22 00:21
How can I debug the generator? I [followed this document](https://github.com/JoanComasFdz/dotnet-how-to-debug-source-generator-vs2022?tab=readme-ov-file#debug-configuration) but get the mentioned error. I have [.NET Compiler Platform SDK](https://docs.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/) installed under Vs 2022 17.10.4

**Comment by MagicAndre1981** [comment] 2024-07-22 00:50
added the generator as csproj to a demo doesn't add the 2 required data

```
OutputItemType="Analyzer"
ReferenceOutputAssembly="false"
```

to the ProjectReference entry and now I can select the debug target to the demo.

**Comment by MagicAndre1981** [comment] 2024-07-22 01:23
with `attributeNode.GetLocation() `in `static KeyValuePair<string, string>? GetAttributes(GeneratorSyntaxContext ctx, CancellationToken token)` I can see the code location and here I only see entries from NrtAssemblyInfo.cs, in GenerateSource() I see the list of attributes (attributes.ToList()) and here they are only added once with the correct data and now I'm confused

**Comment by MagicAndre1981** [comment] 2024-07-22 02:03
now the main application with the nuget reference starts fine inside debugger all code calls fetch the correct data. 

So this looks like a VS bug

**Comment by MagicAndre1981** [comment] 2024-07-23 09:32
> I've updated from 1.5.0-rc.1 to 1.5.0-rc.2 and the issue was gone

ok, the update changed the nuget files in obj folder with the restore data. When I always clean those data, open the solution, let VS write the nuget data again I don't suffer the issue.

**Comment by kzu** [comment] 2024-07-24 01:51
You can switch to the ThisAssembly.Constants instead and only lift the values you are interested in accessing via code. Or alternatively ThisAssembly.Project to lift project properties.

**Comment by kzu** [comment] 2024-07-24 01:56
I'd say the issue is when the patch target runs. It seems to be running inconsistently between full build and design-time builds. To force it to run always BEFORE generators see any code, add the following:

```xml
<Target Name="EnsureNrtPatchAssemblyInfo" 
              BeforeTargets="GenerateMSBuildEditorConfigFileShouldRun" 
              DependsOnTargets="NrtPatchAssemblyInfo" />

```

**Comment by MagicAndre1981** [comment] 2024-07-24 06:36
where should I add this to? I've added this to the `Unclassified.NetRevisionTask.targets`, made a 0.4.4-beta1 nuget and updated my solution to this version, but the same happens again. If the nuget temp data are not available I don't get the issue, but after close and reopening of the solution I get the error again.

**Comment by MagicAndre1981** [comment] 2024-07-24 07:13
the only difference is now that the correct data are on top and the dummy data are added under it (difference to what I saw before as shown in the picture)

**Comment by MagicAndre1981** [comment] 2024-07-24 09:56
the order changes each time now. I also compared the generated nuget/msbuild files after 1st and 2nd load and they don't change.

I'm now out of ideas.

**Comment by kzu** [comment] 2024-08-02 22:41
Report the bug to Unclassified? You add the target to your project file, or a Directory.Build.targets. Or switch to ThisAssembly.Constants instead to avoid collisions. I'm closing this since this isn't planned on my end.

**Closed by kzu** 2024-08-02 22:41 UTC
Labels: enhancement, help wanted, good first issue

**Comment by MagicAndre1981** [comment] 2024-08-05 07:18
I think this is a VS issue. The generated exe has the correct assembly data and I can call them correctly at runtime. 

The `ThisAssembly.AssemblyInfo.g.cs` inside the obj `generated\ThisAssembly.AssemblyInfo\ThisAssembly.AssemblyInfoGenerator` folder has the correct data but when I selct `Go to Definition `and select `Open containing folder` I see empty file in `C:\Users\André\AppData\Local\Temp\VSGeneratedDocuments\8b3f3a52-2fd0-c00f-3c33-22a20ae13471`
