### ISSUE TITLE
Setting GenerateAssemblyInfo=false stops source generator from running

### ISSUE THREAD

**Issue by MagicAndre1981** [devlooped/ThisAssembly#407] opened 2024-09-30 07:27 UTC
## Describe the Bug

After Updating ThisAssembly to from 1.5.0 to 2.0.0 I can no longer access the ThisAssembly.Info properties like `ThisAssembly.Info.Description`

![image](https://github.com/user-attachments/assets/7cb77f11-19df-4646-bb07-de6b83d3b59b)

As they come from 3rd party tools, not from my project:

![image](https://github.com/user-attachments/assets/f37c4daf-e573-4ee6-ae6f-e3b36d43a274)

## Steps to Reproduce

update from "ThisAssembly.AssemblyInfo" to 2.0:

`<PackageReference Include="ThisAssembly.AssemblyInfo" Version="2.0.0">`

## Expected Behavior

code can be called `var Description = ThisAssembly.Info.Description;` fine as in 1.5.0

In my csproj I have set thoise 2 entries:

    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>

and I no longer see the genereted `ThisAssembly.AssemblyInfo.g.cs` file only the `ApplicationConfiguration.g.cs` which includes the generated calls for `ApplicationConfiguration.Initialize();`

[![Back this issue](https://raw.githubusercontent.com/devlooped/SponsorLink/main/docs/assets/img/separator.png "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)
[![Back this issue](https://img.shields.io/badge/backed-%240-EA4AAA?logo=githubsponsors "Back this issue")](https://www.devlooped.com/SponsorLink/github/issues/?s=devlooped)

**Comment by kzu** [comment] 2024-09-30 10:20
Hi there! Some questions:
* Is this an intellisense or a build error? (Try filtering for build in the error list)
* Does it also fail when doing dotnet build in the CLI?
* Does closing and reopening the solution make a difference? 

Thanks!

**Comment by kzu** [comment] 2024-09-30 11:15
I created a new console app, added the package, and verified that the intellisense doesn't work at first, but after first build, it does. Seems to be something in VS since I'm not doing anything different on that front.

![image](https://github.com/user-attachments/assets/6f4a6ec9-0cb5-446f-868a-5408d33ecdf6)

**Comment by kzu** [comment] 2024-09-30 11:25
If you delete bin/obj without closing the source file, you see the same effect:

![image](https://github.com/user-attachments/assets/c095967e-06a3-4b07-8c65-bd20981dbc60)

(note the Build + Intellisense in the drowdown). Doing a "full build" fixes it automatically though.

Does that match your experience?

**Comment by MagicAndre1981** [comment] 2024-09-30 11:29
closing/reopening make no different and also deleting the obj nuget folder makes no difference.

This is a compile error as the generated class is not found I can't compile the project at all no matter if I try it from VS2022 or cli with dotnet.

**Comment by kzu** [comment] 2024-09-30 11:31
Could you share which package you're using? ThisAssembly.AssemblyInfo or ThisAssembly (metadata package)?
Also, would you mind creating a blank console app, adding the same package and using WriteLine as I did above? If you see the same error, would you mind running `dotnet build -bl` and attaching the binlog? 🙏

**Comment by MagicAndre1981** [comment] 2024-09-30 11:35
I use this one:

https://www.nuget.org/packages/ThisAssembly.AssemblyInfo/2.0.0

and before updating I was using the 1.5.0 version which is now unlisted?

https://www.nuget.org/packages/ThisAssembly.AssemblyInfo/1.5.0

I'm now out of office for the rest of the day, I'll try to compare the build with 1.5.0 and 2.0.0 tomorrow.

**Comment by kzu** [comment] 2024-09-30 11:43
Yeah, I have unlisted 1.5 in favor of 2.0.

**Comment by MagicAndre1981** [comment] 2024-10-01 06:53
>  Why is the dll missing? What have you changed?

ok, after looking at the commits (which are horrible as there are a lot of meaningless commits "Bump files with dotnet-file sync" which is awfull to see what commits do, you need to check every commit what is changed) I found this [commit](https://github.com/devlooped/ThisAssembly/commit/a6c207db764509147c66b9ebaa57b7cd72dacd77).

This explains the dependency on `ThisAssembly.Constants` and here is my issue. With [MSBuild Structured Log Viewer](https://msbuildlog.com/) I can see that the task to transfer my assembly infos into constants is not called so the Constants Source generator can only transfer my dummy constants I've added to check if this code generator is called.

![image](https://github.com/user-attachments/assets/0f56218d-860f-4376-bee7-813f7e7be07c)

**Comment by kzu** [comment] 2024-10-01 19:51
`ThisAssembly.AssemblyInfo` is indeed just a special case of Contants (most packages are, now). That should not be the issue at all.

Could you please create a repro project? I simply cannot reproduce your issue as-is. The fact that those targets are greyed out do not indicate much (could have run previously already, for example). Without either a repro project or a binlog, there isn't much I can do :(

**Comment by MagicAndre1981** [comment] 2024-10-02 17:00
I've created a demo that works fine with 1.5.0 and fails with 2.0.3. It is an empty .net 8 WinForms application but includes all reference nugets as in my real application but it depends on subversion for version control.

You need to checkout the code from the repo with svn/TortoiseSVN and open the sln in trunk 

[ThisAssembly.AssemblyInfo.Demo_SVN_Repo.zip](https://github.com/user-attachments/files/17233150/ThisAssembly.AssemblyInfo.Demo_SVN_Repo.zip)

If I downgrade the package to 1.5.0 I get the generated files.

**Comment by MagicAndre1981** [comment] 2024-10-06 06:52
> Could you please create a repro project? I simply cannot reproduce your issue as-is. 

Did you have some time to look at it? You need use `svn checkout file:///` with path to create a working copy and get the project.

**Comment by OoLunar** [comment] 2024-10-07 17:45
Able to reproduce as a first party consumer and with \`dotnet build\` in CLI.

**Comment by OoLunar** [comment] 2024-10-07 18:39
This seems to only happen when upgrading from a previous version. Remove `ThisAssembly` from your `csproj` file, run `dotnet clean`, then readd the updated version through: `dotnet add package ThisAssembly --version 2.0.3`

**Comment by kzu** [comment] 2024-10-08 00:48
Roslyn does heavy caching of intermediate files. I'd suggest deleting bin/obj recursively and try again.

I do not have or use svn to test this locally from the provided zip. I doubt it has anything to do with source control, to a simple zip of the actual sources should be enough if it does repro.

**Comment by MagicAndre1981** [comment] 2024-10-08 05:12
As already said, clearing obj/bin makes no difference.

without svn the code doesn't compile as I've added Unclassified.NetRevisionTask I also use in my project. You wanted all references, you get all references in the demo

**Comment by kzu** [comment] 2024-10-08 13:38
That's great actionable investigation, thanks! I'll look into it ASAP.

**Comment by kzu** [comment] 2024-10-08 18:39
Got the fix 💪 https://github.com/devlooped/ThisAssembly/pull/422

**Closed** 2024-10-08 18:43 UTC
Labels: bug

**Comment by MagicAndre1981** [comment] 2024-10-09 07:47
> Got the fix 💪 #422

nope, still the same error. The translation to constants runs but generates crap (Company gets project name, version is 1.0.0.0 not my version from Unclassified.NetRevisionTask) so the default values. And the Copyright, Description from AssemblyInfo.cs are not translated and so I still have compile error `CS0117: 'ThisAssembly.Info' does not contain a definition for 'Description'`

**Comment by kzu** [comment] 2024-10-15 17:31
It looks like whatever you're using is not playing nice and is generating a non-partial ThisAssembly. Plz bring the issue to them.

Without a repro, it's kinda impossible to see what you see. All my tests and daily usage shows it's working as designed. I have never used that Unclassidified thing.

**Comment by MagicAndre1981** [comment] 2024-10-16 04:47
> Without a repro, it's kinda impossible to see what you see. All my tests and daily usage shows it's working as designed. I have never used that Unclassidified thing.

I've posted a repro which you ignore the whole time. I'll stick on 1.5.0 which works and ignore all newer updates.

**Comment by MagicAndre1981** [comment] 2024-10-16 05:27
and your "fix" is to ignore my configured GenerateAssemblyInfo value and set the values to the data which the SDK sets when GenerateAssemblyInfo is true. And this is what **I DON'T** want. I set the value to **false** for reasons!

**Comment by kzu** [comment] 2024-10-16 18:50
> I do not have or use svn to test this locally from the provided zip. I doubt it has anything to do with source control, to a simple zip of the actual sources should be enough if it does repro.

That is not something I can work off of as a repro. Plz provide a github repo if that is easier for you. 

Could you elaborate on why it's what you DON'T WANT, what I did? I studied the SDK targets carefully and there's no side effect from my fix. You might disagree with how I fixed it, but that's a different matter. What side effect are you seeing that is problematic? Please provide a clean repro I can simply clone or download (without having to install any software), and I can look at it.

**Comment by kzu** [comment] 2024-10-16 18:51
Also, I'd be more than happy to review a PR that fixes it in a better way for your scenario.

**Comment by MagicAndre1981** [comment] 2024-10-22 09:17
Again, there is a sideeffect, your changes causes that [data are read from the csproj](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#package-properties) and no longer from my AssemblyInfo.cs and this causes issues with my consumed [Unclassified.NetRevisionTask](https://www.nuget.org/packages/Unclassified.NetRevisionTask) package. It doesn't support this and the subversion revision is not added to the version. I have to do this as there is [no Subversion SourceLink provider](https://github.com/dotnet/sourcelink/issues/184) , so I need to add the SVN revision to the version number to see which version the user is running so that I can checkout this revision to debug the issue. So I **MUST** set GenerateAssemblyInfo to false. And as I use Subversion, putting this on Github is useless 🤦. I debugged the issue, found the casue, provided you a repro and you only complain and complain.

I've add the working `thisassembly.assemblyinfo.1.5.0.nupkg` now to my solution and added a source entry to the nuget.config to use this solution folder as source, so that restore always works and I'll ignore now all updates of your package and use 1.5.0 until something breaks it

**Comment by kzu** [comment] 2024-10-22 18:58
Well, I guess you can also report to that Unclassified.NetRevisionTask package that they are incompatible with this package. 

As I mentioned, I'd gladly take a PR if this is critical for you. I don't have the bandwidth to do this for free, and this is the first and only time someone ever reported such an issue.

Thanks.
